services:
  database:
    image: postgres:16-bookworm
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password1235
      - POSTGRES_DB=SuperdarkLists
    volumes:
      - ./Volumes/database:/var/lib/postgresql/data
